"use client";

import { useEffect, useState } from "react";
import { Alert, Badge, Button, Card, EmptyState, Field, Input, Modal, PageHeader, Spinner, Table } from "@duga/ui";
import { api } from "@/lib/client/api";

type Staff = { id: string; firstName: string; lastName: string; role: string; salaryProfile?: { monthlyAmount: number; latePenalty: number; rewardAmount: number } | null };
type Entry = { id: string; userId: string; baseSalary: number; lateDays: number; lateDeduction: number; reward: number; extraDeduction: number; netPay: number; status: string; note?: string | null; user: { firstName: string; lastName: string; role: string } };
const money = (v: number | string) => `₦${Number(v ?? 0).toLocaleString()}`;

export default function PayrollPage() {
  const [role, setRole] = useState(""); const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const [staff, setStaff] = useState<Staff[]>([]); const [entries, setEntries] = useState<Entry[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [salaryStaff, setSalaryStaff] = useState<Staff | null>(null); const [edit, setEdit] = useState<Entry | null>(null); const [form, setForm] = useState<Record<string, string>>({}); const [bursarAccess, setBursarAccess] = useState(false);
  async function load() { setLoading(true); try { const data = await api<{ role: string; staff: Staff[]; entries: Entry[]; bursarAccess: boolean }>(`payroll?month=${month}`); setRole(data.role); setStaff(data.staff); setEntries(data.entries); setBursarAccess(data.bursarAccess); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [month]);
  async function generate() { try { await api("payroll/generate", { method: "POST", body: { month } }); await load(); } catch (e) { alert((e as Error).message); } }
  async function saveSalary() { if (!salaryStaff) return; try { await api("payroll/setSalary", { method: "POST", body: { userId: salaryStaff.id, monthlyAmount: Number(form.monthlyAmount), latePenalty: Number(form.latePenalty), rewardAmount: Number(form.rewardAmount) } }); setSalaryStaff(null); await load(); } catch (e) { alert((e as Error).message); } }
  async function saveAdjustment() { if (!edit) return; try { await api(`payroll/${edit.id}/adjust`, { method: "POST", body: { lateDays: Number(form.lateDays), reward: Number(form.reward), extraDeduction: Number(form.extraDeduction), note: form.note } }); setEdit(null); await load(); } catch (e) { alert((e as Error).message); } }
  async function paid(id: string) { try { await api(`payroll/${id}/markPaid`, { method: "POST", body: {} }); await load(); } catch (e) { alert((e as Error).message); } }
  async function toggleBursar() { try { await api("payroll/setBursarAccess", { method: "POST", body: { enabled: !bursarAccess } }); setBursarAccess(!bursarAccess); } catch (e) { alert((e as Error).message); } }
  if (loading) return <Spinner size={28} />; if (error) return <Alert tone="danger">{error}</Alert>;
  return <div><PageHeader title="Payroll" subtitle="Monthly salaries, late-coming penalties, rewards and deductions." actions={<Button onClick={generate}>Generate {month} payroll</Button>} />
    {role === "OWNER" && <Card title="Bursar access" style={{ marginBottom: 16 }}><p>The bursar can manage fees and payroll only when you grant access.</p><Button variant={bursarAccess ? "outline" : "primary"} onClick={toggleBursar}>{bursarAccess ? "Remove bursar finance access" : "Grant bursar finance access"}</Button></Card>}
    {role === "OWNER" && <Card title="Staff salary rules" style={{ marginBottom: 16 }}><Table headers={["Staff", "Role", "Monthly salary", "Late penalty/day", "Monthly reward", ""]}>{staff.map(s => <tr key={s.id}><td>{s.firstName} {s.lastName}</td><td>{s.role}</td><td>{money(s.salaryProfile?.monthlyAmount ?? 0)}</td><td>{money(s.salaryProfile?.latePenalty ?? 0)}</td><td>{money(s.salaryProfile?.rewardAmount ?? 0)}</td><td><Button size="sm" variant="outline" onClick={() => { setSalaryStaff(s); setForm({ monthlyAmount: String(s.salaryProfile?.monthlyAmount ?? 0), latePenalty: String(s.salaryProfile?.latePenalty ?? 0), rewardAmount: String(s.salaryProfile?.rewardAmount ?? 0) }); }}>Set rules</Button></td></tr>)}</Table></Card>}
    {entries.length === 0 ? <EmptyState title="No payroll entries" hint="Set staff salary rules, then generate the monthly payroll." /> : <Card title={`Payroll — ${month}`}><Table headers={["Staff", "Base", "Late days", "Late deduction", "Reward", "Other deduction", "Net pay", "Status", ""]}>{entries.map(e => <tr key={e.id}><td>{e.user.firstName} {e.user.lastName}</td><td>{money(e.baseSalary)}</td><td>{e.lateDays}</td><td>{money(e.lateDeduction)}</td><td>{money(e.reward)}</td><td>{money(e.extraDeduction)}</td><td><b>{money(e.netPay)}</b></td><td><Badge tone={e.status === "PAID" ? "success" : "warning"}>{e.status}</Badge></td><td>{e.status !== "PAID" && <><Button size="sm" variant="outline" onClick={() => { setEdit(e); setForm({ lateDays: String(e.lateDays), reward: String(e.reward), extraDeduction: String(e.extraDeduction), note: e.note ?? "" }); }}>Adjust</Button> <Button size="sm" onClick={() => paid(e.id)}>Mark paid</Button></>}</td></tr>)}</Table></Card>}
    <Modal open={!!salaryStaff} onClose={() => setSalaryStaff(null)} title="Set salary rules"><Field label="Monthly salary"><Input type="number" value={form.monthlyAmount ?? ""} onChange={e => setForm({ ...form, monthlyAmount: e.target.value })} /></Field><Field label="Penalty per late day"><Input type="number" value={form.latePenalty ?? ""} onChange={e => setForm({ ...form, latePenalty: e.target.value })} /></Field><Field label="Monthly reward"><Input type="number" value={form.rewardAmount ?? ""} onChange={e => setForm({ ...form, rewardAmount: e.target.value })} /></Field><Button onClick={saveSalary}>Save salary rules</Button></Modal>
    <Modal open={!!edit} onClose={() => setEdit(null)} title="Adjust payroll"><Field label="Late days"><Input type="number" value={form.lateDays ?? "0"} onChange={e => setForm({ ...form, lateDays: e.target.value })} /></Field><Field label="Reward"><Input type="number" value={form.reward ?? "0"} onChange={e => setForm({ ...form, reward: e.target.value })} /></Field><Field label="Other deduction"><Input type="number" value={form.extraDeduction ?? "0"} onChange={e => setForm({ ...form, extraDeduction: e.target.value })} /></Field><Field label="Note"><Input value={form.note ?? ""} onChange={e => setForm({ ...form, note: e.target.value })} /></Field><Button onClick={saveAdjustment}>Save adjustment</Button></Modal>
  </div>;
}
